/**
 * custom header SignatureLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { BaseController } from './baseController';

export class CustomHeaderSignatureController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getCustomHeaderSignature(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET', '/auth/customHeaderSignature');
    return req.callAsText(requestOptions);
  }
}
