"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createPagedData = exports.isNumberPagedResponse = exports.createNumberPagedResponse = exports.isLinkPagedResponse = exports.createLinkPagedResponse = exports.isCursorPagedResponse = exports.createCursorPagedResponse = exports.isOffsetPagedResponse = exports.createOffsetPagedResponse = exports.LinkPagination = exports.PagePagination = exports.CursorPagination = exports.OffsetPagination = void 0;
var offsetPagination_1 = require("./offset/offsetPagination");
Object.defineProperty(exports, "OffsetPagination", { enumerable: true, get: function () { return offsetPagination_1.OffsetPagination; } });
var cursorPagination_1 = require("./cursor/cursorPagination");
Object.defineProperty(exports, "CursorPagination", { enumerable: true, get: function () { return cursorPagination_1.CursorPagination; } });
var pagePagination_1 = require("./page/pagePagination");
Object.defineProperty(exports, "PagePagination", { enumerable: true, get: function () { return pagePagination_1.PagePagination; } });
var linkPagination_1 = require("./link/linkPagination");
Object.defineProperty(exports, "LinkPagination", { enumerable: true, get: function () { return linkPagination_1.LinkPagination; } });
var offsetPagedResponse_1 = require("./offset/offsetPagedResponse");
Object.defineProperty(exports, "createOffsetPagedResponse", { enumerable: true, get: function () { return offsetPagedResponse_1.createOffsetPagedResponse; } });
Object.defineProperty(exports, "isOffsetPagedResponse", { enumerable: true, get: function () { return offsetPagedResponse_1.isOffsetPagedResponse; } });
var cursorPagedResponse_1 = require("./cursor/cursorPagedResponse");
Object.defineProperty(exports, "createCursorPagedResponse", { enumerable: true, get: function () { return cursorPagedResponse_1.createCursorPagedResponse; } });
Object.defineProperty(exports, "isCursorPagedResponse", { enumerable: true, get: function () { return cursorPagedResponse_1.isCursorPagedResponse; } });
var linkPagedResponse_1 = require("./link/linkPagedResponse");
Object.defineProperty(exports, "createLinkPagedResponse", { enumerable: true, get: function () { return linkPagedResponse_1.createLinkPagedResponse; } });
Object.defineProperty(exports, "isLinkPagedResponse", { enumerable: true, get: function () { return linkPagedResponse_1.isLinkPagedResponse; } });
var numberPagedResponse_1 = require("./page/numberPagedResponse");
Object.defineProperty(exports, "createNumberPagedResponse", { enumerable: true, get: function () { return numberPagedResponse_1.createNumberPagedResponse; } });
Object.defineProperty(exports, "isNumberPagedResponse", { enumerable: true, get: function () { return numberPagedResponse_1.isNumberPagedResponse; } });
var pagedData_1 = require("./pagedData");
Object.defineProperty(exports, "createPagedData", { enumerable: true, get: function () { return pagedData_1.createPagedData; } });
