name: Deploy to Git
run-name: Deploying to Git branch ${{ github.ref_name }}-DEPLOYED

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0  # Ensure the full history is fetched to push changes back

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      
      - name: Install dependencies and build
        run: |
          rm -f .gitignore
          yarn install --frozen-lockfile
          yarn build

      - name: Push forcefully to new branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          DEPLOY_BRANCH="${{ github.ref_name }}-DEPLOYED"

           # Check if the remote branch exists and delete it
          if git ls-remote --exit-code --heads origin "$DEPLOY_BRANCH"; then
            git push origin --delete "$DEPLOY_BRANCH"
          fi

          # Create and push the new branch
          git checkout -b "$DEPLOY_BRANCH"
          git add -A
          git commit -m "build: deploys changes from ${{ github.ref_name }}"
          git push origin "$DEPLOY_BRANCH" --force
