name: CI
on: [push]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x", "17.x", "18.x", "19.x", "22.x"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Remove mcp-core for Node < 22
        if: ${{ !startsWith(matrix.node, '22') }}
        run: rm -rf packages/mcp-core

      - name: Install deps
        run: yarn

      - name: Check for endpointMetadataFromId.ts
        run: |
          echo "Listing src directory..."
          ls -l src
          echo "Searching for endpointMetadataFromId.ts..."
          find src -iname "endpointMetadataFromId.ts" || echo "File not found"
          echo "Listing src directory..."
          ls -l src
          echo "Searching for coreClient.ts..."
          find src -iname "coreClient.ts" || echo "File not found"
      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Code formatting
        run: yarn check-style
